# @package task
project: smpl_hoi
name: SMPL-HOI

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: smpl
# objects:
#   - name: cloth_stand
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: active_adaptation.envs.mdp.action.JointPosition
    action_scaling: {
      .*_(Hip|Knee|Ankle).*: 0.5,
      (Torso|Spine|Chest|L_Thorax|R_Thorax).*: 0.5,
    }
    alpha_range: [0.7, 0.9]

# command:
#   class: HOITracking
#   motion_clip_dir: null
#   data_path: null

command:
  class: Twist
  linvel_x_range: [-0.8, 1.4]
  linvel_y_range: [-0.8, 0.8]
  angvel_range: [-2.0, 2.0]
  yaw_stiffness_range: [0.5, 1.0]
  use_stiffness_ratio: 0.9
  stand_prob: 0.05

observation:
  policy:
    command:
    root_angvel_b: {}
    root_linvel_b: {}
    gravity_multistep: {steps: 4, noise_std: 0.05}
    joint_pos_multistep: {steps: 4, noise_std: 0.05}
    joint_vel_multistep: {steps: 4, noise_std: 0.2}

reward:
  loco:
    linvel_exp:         {weight: 1.5, dim: 2}
    linvel_projection:  {weight: 0.5}
    angvel_z_exp:       {weight: 1.2, gamma: 0.8}
  reg:
    survival:           {weight: 2.0}
    energy_l1:          {weight: 2.0e-4}
    joint_acc_l2:       {weight: 1.0e-7}
    
    action_rate_l2:     {weight: 0.005}
    action_rate2_l2:    {weight: 0.005}

randomization:
  reset_joint_states_uniform:
    pos_ranges:
      .*: [-0.1, 0.1]
    rel: true

termination:
  crash:
    body_names_expr:
      - (Pelvis|Spine|Chest|Neck|Head)
      - (L_Hip|R_Hip|L_Knee|R_Knee)
#   fall_over: {xy_thres: 0.9}

