# @package task
project: smpl_hoi
name: SMPL-HOI

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: smpl
objects:
  - name: largebox
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.033
  isaac_physics_dt: 0.0167
  mujoco_physics_dt: 0.003
  gpu_max_rigid_patch_count: 262144 # 2**18

input:
  action:
    _target_: active_adaptation.envs.mdp.action.JointPosition
    action_scaling: {
      .*(Hip|Torso|Knee|Ankle|Shoulder|Elbow|Wrist).*: 0.5,
      .*(Index|Middle|Pinky|Ring|Thumb).*: 0.1,
    }
    alpha_range: [0.7, 0.9]

command:
  class: SMPLHOITask
  motion_file: sub12_largebox_000_replay.pkl
  key_body: [ 
              "Pelvis",
              "L_Hip", "L_Knee", "L_Ankle", "L_Toe", 
              "R_Hip", "R_Knee", "R_Ankle", "R_Toe", 
              "Torso", "Spine", "Chest", "Neck", "Head", 
              "L_Thorax", "L_Shoulder", "L_Elbow", "L_Wrist", 
              "R_Thorax", "R_Shoulder", "R_Elbow", "R_Wrist"
            ]

observation:
  policy:
    root_height:    {}
    body_pos_local: {}
    body_ori_local: {}
    body_linvel_local: {}
    body_angvel_local: {}
    contact: {}
    ref_body_gap: {}
    ref_body_linvel_gap: {}
    ref_body_angvel_gap: {}

    ref_obj_gap: {}
    ref_obj_linvel_gap: {}
    ref_obj_angvel_gap: {}

    # interaction_guidance: {}

reward:
  loco:
    track_kp:       {weight: 1.0}
    track_obj:      {weight: 1.0}
    track_cg:       {weight: 1.0}
    
    joint_acc_l2:   {weight: 1.0e-7}

# randomization:
#   reset_joint_states_uniform:
#     pos_ranges:
#       .*: [-0.01, 0.01]
#     rel: true

termination:
  max_timesteps:  {}
  body_pos_reset: {}
  obj_pos_reset:  {}
  cg_reset:       {}
