# @package task
project: smpl_hoi
name: SMPL-HOI

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: smpl
objects:
  # - name: largebox
  - name: plasticbox
  # - name: smalltable
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: ${frac:1/30}
  isaac_physics_dt: ${frac:1/120}
  mujoco_physics_dt: ${frac:1/300}
  physx:
    gpu_max_rigid_patch_count: ${eval:'2**18'}
    # enable_ccd: true

input:
  action:
    _target_: active_adaptation.envs.mdp.action.JointPosition
    action_scaling: {
      .*(Hip|Torso|Knee|Ankle|Shoulder|Elbow|Wrist).*: 1.0,
      .*(Index|Middle|Pinky|Ring|Thumb).*: 1.0,
    }
    alpha_range: [0.7, 0.9]

command:
  class: SMPLHOITask
  motion_file: sub12_plasticbox_000.pkl
  key_body: [ 
              "Pelvis",
              ".*Hip", ".*Knee", ".*Ankle", ".*Toe", 
              "Torso", "Spine", "Chest", "Neck", "Head", 
              ".*Thorax", ".*Shoulder", ".*Elbow", ".*Wrist", 
              # ".*Index3", ".*Middle3", ".*Pinky3", ".*Ring3",".*Thumb3"
            ]

observation:
  policy:
    root_height:    {}
    body_pos_local: {}
    body_ori_local: {}
    body_linvel_local: {}
    body_angvel_local: {}
    contact: {}
    ref_body_gap: {}
    ref_body_linvel_gap: {}
    ref_body_angvel_gap: {}

    ref_obj_gap: {}
    ref_obj_linvel_gap: {}
    ref_obj_angvel_gap: {}

    # interaction_guidance: {}

reward:
  _mult_dt_:        false
  loco:
    track_kp:       {weight: 1.0}
    track_obj:      {weight: 1.0}
    track_cg:       {weight: 1.0}
    _eval_:         "lambda *args: args[0] * args[1] * args[2]"

  reg:
    action_rate_l2: {weight: 5e-5}

# randomization:
#   reset_joint_states_uniform:
#     pos_ranges:
#       .*: [-0.01, 0.01]
#     rel: true

termination:
  max_timesteps:  {}
  body_pos_reset: {}
  obj_pos_reset:  {}
  cg_reset:       {}
